### ISSUE TITLE
ProcessTimedOutException: The process "'pohoda-transaction-report' "

### ISSUE THREAD

**Issue by Vitexus** [VitexSoftware/multiflexi-common#17]
```
Nov 29 09:08:21 se-zabbix-proxy php[2114429]: PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\ProcessTimedOutException: The process "'pohoda-transaction-report' """ exceeded the timeout of 32767 >
Nov 29 09:08:21 se-zabbix-proxy php[2114429]: Stack trace:
Nov 29 09:08:21 se-zabbix-proxy php[2114429]: #0 /var/lib/composer/multiflexi/symfony/process/Process.php(451): Symfony\Component\Process\Process->checkTimeout()
Nov 29 09:08:21 se-zabbix-proxy php[2114429]: #1 /var/lib/composer/multiflexi/symfony/process/Process.php(252): Symfony\Component\Process\Process->wait()
Nov 29 09:08:21 se-zabbix-proxy php[2114429]: #2 /usr/lib/multiflexi/MultiFlexi/Executor/Native.php(62): Symfony\Component\Process\Process->run()
Nov 29 09:08:21 se-zabbix-proxy php[2114429]: #3 /usr/lib/multiflexi/MultiFlexi/Executor/Native.php(84): MultiFlexi\Executor\Native->launch()
Nov 29 09:08:21 se-zabbix-proxy php[2114429]: #4 /usr/lib/multiflexi/MultiFlexi/Job.php(436): MultiFlexi\Executor\Native->launchJob()
Nov 29 09:08:21 se-zabbix-proxy php[2114429]: #5 /usr/lib/multiflexi/daemon.php(44): MultiFlexi\Job->performJob()
Nov 29 09:08:21 se-zabbix-proxy php[2114429]: #6 {main}
Nov 29 09:08:21 se-zabbix-proxy php[2114429]:   thrown in /var/lib/composer/multiflexi/symfony/process/Process.php on line 1182
Nov 29 09:08:21 se-zabbix-proxy systemd[1]: multiflexi.service: Main process exited, code=exited, status=255/EXCEPTION
```

**Comment by Vitexus** [comment]
Closing as done. `php-vitexsoftware-multiflexi-core/src/MultiFlexi/Executor/Native.php` now wraps the same 32767s Symfony Process timeout in a try/catch, converting it to a logged status instead of an uncaught fatal `ProcessTimedOutException`. Reopen if the timeout still crashes the process.
